print("расположи в правильном порядке: H. habilis, H. erectus, H. rudolfensis, H. georgicus, H. ergaster, H. antecessor, H. cepranensis, H. heidelbergensis, H. neanderthalensis, H. rhodesiensis, H. sapiens sapiens")
a1=input()
a2=input()
a3=input()
a4=input()
a5=input()
a6=input()
a7=input()
a8=input()
a9=input()
a10=input()
a11=input()
print(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,sep="=>")